### ISSUE TITLE
ender slab destroys items

### ISSUE THREAD

**Issue by FaultyPixel** [i509VCB/CursedShulkerBoxes#10]
with the following setup : 
![2020-04-25_17 50 34](https://user-images.githubusercontent.com/64114112/80284204-56e6f780-871d-11ea-8183-45a982b8a9cf.png)

items put in the hopper will leave the hoppers : 
![2020-04-25_17 49 52](https://user-images.githubusercontent.com/64114112/80284195-4767ae80-871d-11ea-82bd-37ce967225c6.png)

But they never make it in the ender shulker slab :
![2020-04-25_17 49 58](https://user-images.githubusercontent.com/64114112/80284200-4fbfe980-871d-11ea-9d22-927bc5fa0b76.png)

**Comment by i509VCB** [comment]
Hmm, I intended this to be like an ender chest (which I recall you can't pump items into). I think the solution to that is copying the item handling code from the ender chest, or further abstract the ender slab from the rest of the shulker boxes. (since the inheirtence stuff in bulky shulkies is out of whack).

The latter is the better solution but I don't see any easy way to do it to 1.15 branch due to the 1.16 branch starting to deviate quite heavily due to some internal changes for new shulker box types.

**Comment by FaultyPixel** [comment]
Yeah i first i was expecting it to behave like an enderchest and not accept items so i was pretty surprised when i saw items being taken from the hopper

**Comment by i509VCB** [comment]
The latest commit on 1.16.x does fix this, but it's still a bit unstable since I just reworked the inheritance a bit so it's all over the place.

**Comment by i509VCB** [comment]
Fixed in 1.16 branch
